FROM ruby:2.6.1-stretch

# Change to the application's directory
WORKDIR /application

# Set Rails environment to production
ENV RAILS_ENV development

RUN apt-get update && apt-get install -qq -y build-essential nodejs --fix-missing --no-install-recommends

# Install gems, nodejs and precompile the assets
RUN gem install bundler

COPY Gemfile* ./
RUN bundle install

# Copy application code
COPY . /application/

RUN bundle exec rails db:migrate

# Start the server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
